print("Enter 2 numbers (only integer")
num1 = input()
num2 = input()
print("The addition is : ",int(num1) + int(num2) )
print("Enter 2 numbers (only float")
num1 = input()
num2 = input()
print("The addition is : ",float(num1) + float(num2) )
print("Enter 2 numbers (int, float")
num1 = input()
num2 = input()
print("The addition is : ",int(num1) + float(num2) )
print("Enter 2 numbers (float,int")
num1 = input()
num2 = input()
print("The addition is : ",float(num1) + int(num2) )
